Repository pknu-wap/WAG, pull requests merged in 2024-09, with the labels that each got.

#468 #465 1인용 미니게임 링크 추가
  client/src/main/MainPage.tsx
Labels: feature, 프론트엔드, 장홍준

#470 Release 배포
  client/public/index.html
  client/src/main/MainPage.tsx
Labels: develop

#471 Release 배포 : 관심도 이슈 예상으로 이름 변경 hot fix
  client/src/main/MainPage.tsx
Labels: develop

#474 feature: 미니게임 랭킹 기능 추가
  server/src/main/java/com/example/server/controller/MiniGameController.java
  server/src/main/java/com/example/server/domain/MiniGameRanking.java
  server/src/main/java/com/example/server/dto/MiniGameRankingDto.java
  server/src/main/java/com/example/server/payload/request/MiniGameRankingRequest.java
  server/src/main/java/com/example/server/payload/response/MiniGameRankingResponse.java
  server/src/main/java/com/example/server/repository/MiniGameRepository.java
  server/src/main/java/com/example/server/service/MiniGameService.java
Labels: feature, 백엔드, 김종경

#487 SEO 및 사용자 경험 최적화 (title 태그, OG태그 description, image 변경)
  client/public/images/Sechan_Face.png
  client/public/images/WAG_Preview_image2.png
  client/public/images/WAG_main_page.png
  client/public/index.html
Labels: feature, 프론트엔드, 김준서

#488 #477 효과음 딜레이 픽스 및 제거 기능
  client/public/audio/darkmode_wag.mp3
  client/public/audio/lightmode_wag.mp3
  client/public/images/yangSaeChanGame.png
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/layout/Footer.tsx
  client/src/components/layout/Header.tsx
  client/src/index.tsx
  client/src/main/MainPage.tsx
  client/src/recoil/recoil.ts
Labels: feature, fix, 프론트엔드, 장홍준

#490 release 배포
  client/public/audio/darkmode_wag.mp3
  client/public/audio/lightmode_wag.mp3
  client/public/images/Sechan_Face.png
  client/public/images/WAG_Preview_image2.png
  client/public/images/WAG_main_page.png
  client/public/images/yangSaeChanGame.png
  client/public/index.html
  client/public/manifest.json
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/layout/Footer.tsx
  client/src/components/layout/Header.tsx
  client/src/index.tsx
  client/src/main/MainPage.tsx
  client/src/recoil/recoil.ts
  server/src/main/java/com/example/server/domain/MiniGameRanking.java
  server/src/main/java/com/example/server/dto/MiniGameRankingDto.java
  server/src/main/java/com/example/server/payload/request/MiniGameRankingRequest.java
  server/src/main/java/com/example/server/service/MiniGameService.java
Labels: develop

#494 #493 footer로 인한 수직 스크롤 제거
  client/src/components/layout/Footer.tsx
  client/src/components/layout/Header.tsx
  client/src/index.css
  client/src/index.tsx
Labels: fix, 프론트엔드, 장홍준

#495 release v1.0.1 배포
  client/src/components/layout/Footer.tsx
  client/src/components/layout/Header.tsx
  client/src/index.css
  client/src/index.tsx
Labels: develop

#497 Fix/#496 모바일 UI 중앙정렬 버그 픽스
  client/src/App.tsx
  client/src/components/layout/Footer.tsx
  client/src/index.tsx
  client/src/main/MainPage.tsx
Labels: fix, 프론트엔드, 장홍준
