Repository pknu-wap/WAG, pull requests merged in 2024-05, with the labels that each got.

#85 파비콘 변경 및 폰트 파일 수정
  client/public/favicon.ico
  client/src/Fonts/Galmuri11-Bold.bdf
  client/src/Fonts/Galmuri11.bdf
  client/src/Fonts/Galmuri7.bdf
  client/src/Fonts/Galmuri9.bdf
  client/src/Fonts/g11_mod.bdf
  client/src/Fonts/g11b_mod.bdf
  client/src/Fonts/g7_mod.bdf
  client/src/Fonts/g9_mod.bdf
Labels: fix, 프론트엔드, 김준서

#93 메인페이지 웹소켓 구독 완료
  client/src/main/MainPage.tsx
Labels: feature, 프론트엔드, 김준서

#95 게임대기방 모달창 제작 연동
  client/package-lock.json
  client/package.json
  client/setupProxy.js
  client/src/Game/ReadyToGame.tsx
  client/src/components/modal/ReadyModal.tsx
  client/src/main/MainPage.tsx
  client/src/recoil/modal.ts
  client/src/types/dto.ts
  client/tailwind.config.js
Labels: feature, 프론트엔드, 하준서

#98 입장코드 입력 연동
  client/src/Game/ReadyToGame.tsx
  client/src/api/gameroomInfo.ts
  client/src/main/MainPage.tsx
  client/src/types/dto.ts
Labels: feature, 프론트엔드, 하준서

#99 방 생성 기능 구현
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/types/dto.ts
Labels: feature, 프론트엔드, 장홍준

#103 ReactModal esc 키로 닫기 비활성화
  client/src/components/modal/ReadyModal.tsx
Labels: fix, 프론트엔드, 장홍준

#104 채팅방 구현 성공
  client/src/Game/ReadyToGame.tsx
  client/src/components/chatBubble/ChatBubble.tsx
  client/src/main/MainPage.tsx
  client/src/recoil/modal.ts
  client/src/types/dto.ts
Labels: feature

#109 #107 코드 수정
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/main/MainPage.tsx
Labels: fix, 백엔드, 프론트엔드, 김종경, 장홍준, 하준서, 김준서, 함규빈

#114 모달 콘솔 오류 수정 완료
  client/src/index.tsx
Labels: fix, 프론트엔드, 김준서

#116 텍스트필드 초기화, 엔터키 적용
  client/src/Game/ReadyToGame.tsx
Labels: feature, 프론트엔드, 하준서

#119 Feature/#117 입장,퇴장 알림
  client/src/Game/ReadyToGame.tsx
  client/src/components/chatBubble/ChatBubble.tsx
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
Labels: feature, 프론트엔드, 김종경

#120 입장 & 퇴장 알림 추가
  client/package-lock.json
  client/package.json
  client/src/Game/ReadyToGame.tsx
  client/src/components/chatBubble/ChatBubble.tsx
  client/src/index.tsx
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
Labels: develop

#127 방 생성
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
Labels: 프론트엔드, 김종경, modify

#131 fix : 비공개방 버그 해결
  client/src/CreateRoom/CreateRoom.tsx
Labels: fix, 프론트엔드, 장홍준

#129 빈 채팅 전달 막기 & CSS 약간 수정
  client/src/Game/ReadyToGame.tsx
  client/src/components/gameIcon/GameIcon.tsx
Labels: feature, 프론트엔드, 김준서

#136 404 컴포넌트 생성
  client/src/App.tsx
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/gameIcon/GameIcon.tsx
  client/src/components/layout/404.tsx
  client/src/main/MainPage.tsx
Labels: feature, 프론트엔드, 하준서

#138 대기방 유저프로필 추가
  client/src/Game/ReadyToGame.tsx
  client/src/api/index.ts
  client/src/api/joinRoom.ts
  client/src/components/ingameComponents/ChatBubble.tsx
  client/src/components/ingameComponents/GameIcon.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/types/dto.ts
Labels: feature, 프론트엔드, 하준서

#144 비공개방 입장 버그 해결
  client/src/main/MainPage.tsx
Labels: fix, 프론트엔드, 장홍준

#152 대기방 방장기능 추가
  client/src/Game/ReadyToGame.tsx
  client/src/components/button/IconButton.tsx
  client/src/components/modal/CaptainReadyModal.tsx
  client/src/index.css
  client/src/recoil/modal.ts
  client/src/types/dto.ts
Labels: feature, 프론트엔드, 하준서

#154 백엔드 도메인 변경으로 API 주소 변경
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/main/MainPage.tsx
Labels: 프론트엔드, 장홍준, modify

#155 release 배포
  client/src/App.tsx
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/api/index.ts
  client/src/api/joinRoom.ts
  client/src/components/button/IconButton.tsx
  client/src/components/ingameComponents/ChatBubble.tsx
  client/src/components/ingameComponents/GameIcon.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/components/layout/404.tsx
  client/src/components/modal/CaptainReadyModal.tsx
  client/src/index.css
  client/src/main/MainPage.tsx
  client/src/recoil/modal.ts
  client/src/types/dto.ts
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/example/server/config/SecurityConfig.java
  server/src/main/java/com/example/server/controller/AuthController.java
  server/src/main/java/com/example/server/controller/ChatController.java
  server/src/main/java/com/example/server/controller/RoomController.java
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/domain/AnswerList.java
  server/src/main/java/com/example/server/domain/GameRecord.java
  server/src/main/java/com/example/server/domain/RoomUser.java
  server/src/main/java/com/example/server/domain/User.java
  server/src/main/java/com/example/server/dto/ChatGameMessage.java
  server/src/main/java/com/example/server/dto/ChatMessage.java
  server/src/main/java/com/example/server/dto/ChatRoomInfoMessage.java
  server/src/main/java/com/example/server/dto/UserDto.java
  server/src/main/java/com/example/server/payload/request/LoginRequest.java
  server/src/main/java/com/example/server/payload/request/SignUpRequest.java
  server/src/main/java/com/example/server/payload/response/ApiResponse.java
  server/src/main/java/com/example/server/payload/response/AuthResponse.java
  server/src/main/java/com/example/server/payload/response/ResultResponse.java
  server/src/main/java/com/example/server/repository/GameRecordRepository.java
  server/src/main/java/com/example/server/repository/RoomRepository.java
  server/src/main/java/com/example/server/repository/RoomUserRepository.java
  server/src/main/java/com/example/server/repository/UserRepository.java
  server/src/main/java/com/example/server/security/CustomUserDetailsService.java
  server/src/main/java/com/example/server/security/TokenProvider.java
  server/src/main/java/com/example/server/security/UserPrincipal.java
  server/src/main/java/com/example/server/security/oauth2/CustomOAuth2UserService.java
  server/src/main/java/com/example/server/service/ChatGptService.java
  server/src/main/java/com/example/server/service/ChatService.java
  server/src/main/java/com/example/server/service/MyPageService.java
  server/src/main/java/com/example/server/service/RoomService.java
Labels: develop, 장홍준

#162 대기방 UI 개선
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/ingameComponents/ChatBubble.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/components/layout/FullLayout.tsx
  client/src/components/modal/CaptainReadyModal.tsx
  client/src/components/modal/Modal.tsx
  client/src/components/modal/ReadyModal.tsx
  client/src/index.css
  client/src/main/MainPage.tsx
  client/src/types/dto.ts
Labels: feature, fix, 프론트엔드, 하준서

#163 release 배포
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/ingameComponents/ChatBubble.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/components/layout/FullLayout.tsx
  client/src/components/modal/CaptainReadyModal.tsx
  client/src/components/modal/Modal.tsx
  client/src/components/modal/ReadyModal.tsx
  client/src/index.css
  client/src/main/MainPage.tsx
  client/src/types/dto.ts
  server/src/main/java/com/example/server/config/WebSocketConfig.java
  server/src/main/java/com/example/server/controller/ChatController.java
  server/src/main/java/com/example/server/controller/RoomController.java
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/payload/response/RoomResponse.java
  server/src/main/java/com/example/server/service/ChatService.java
  server/src/main/java/com/example/server/service/NickNameService.java
  server/src/main/java/com/example/server/service/RoomService.java
  server/src/main/resources/static/WAG01.png
  server/src/main/resources/static/index.html
Labels: develop, 장홍준

#164 대기방 방장 위임
  client/src/Game/ReadyToGame.tsx
Labels: feature, 프론트엔드, 하준서

#166 게임 시작, 정답 및 질문(답변) 외치기 로직 구현
  client/src/Game/ReadyToGame.tsx
Labels: feature, 프론트엔드, 김준서

#172 채팅창 컴포넌트 세분화
  client/src/Game/ReadyToGame.tsx
  client/src/components/chatRoom/ChatRoom.tsx
  client/src/components/chatRoom/NotificationMessage.tsx
  client/src/components/chatRoom/UserMessage.tsx
  client/src/components/ingameComponents/ChatBubble.tsx
Labels: refactor, 프론트엔드, 김준서

#174 방 인원수 표시 기능 추가, 방장 권한 넘기기 오류 수정
  client/src/Game/ReadyToGame.tsx
Labels: feature, fix, 프론트엔드, 김준서

#178 뒤로가기 새로고침 막아놓기
  client/package-lock.json
  client/package.json
  client/src/Game/ReadyToGame.tsx
  client/src/util/history.ts
Labels: fix, 프론트엔드, 하준서

#177 Toast 기능 추가 및 코드 개선
  client/package-lock.json
  client/package.json
  client/src/Game/ReadyToGame.tsx
  client/src/components/toast/Toast.tsx
  client/src/index.tsx
Labels: feature, 프론트엔드, 김준서

#180 모달 오픈 시 뒤로가기 가능
  client/src/Game/ReadyToGame.tsx
Labels: fix, 프론트엔드, 하준서

#182 modify/#181-정답어 api 수정
  server/src/main/java/com/example/server/payload/response/AnswerListResponse.java
  server/src/main/java/com/example/server/repository/GameOrderRepository.java
  server/src/main/java/com/example/server/service/ChatService.java
Labels: 백엔드, 김종경, modify

#186 나가기 기능 추가
  client/src/Game/ReadyToGame.tsx
Labels: fix, 프론트엔드, 하준서

#187 feature/#185-경고
  server/src/main/java/com/example/server/dto/ChatMessage.java
  server/src/main/java/com/example/server/exception/MaxPenaltyExceededException.java
  server/src/main/java/com/example/server/repository/GameOrderRepository.java
  server/src/main/java/com/example/server/service/ChatService.java
Labels: feature, 백엔드, 김종경

#190 게임시작 이후 턴마다 돌아가는 타이머 추가
  client/package-lock.json
  client/package.json
  client/src/Game/ReadyToGame.tsx
  client/src/Game/timer/Timer.tsx
  client/src/Game/timer/styled.ts
  client/src/Game/timer/useTimer.ts
  client/src/components/chatRoom/ChatRoom.tsx
  client/src/components/ingameComponents/ChatBubble.tsx
  client/src/components/ingameComponents/GameIcon.tsx
  client/src/types/common.ts
  client/src/types/dto.ts
Labels: feature, 프론트엔드, 김준서

#198 modify/#197-ASK-수정
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/repository/GameOrderRepository.java
  server/src/main/java/com/example/server/repository/RoomUserRepository.java
  server/src/main/java/com/example/server/service/ChatService.java
Labels: 백엔드, 김종경, modify

#202 feature/#201-게임_진행_중_탈주_처리
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/dto/ChatMessage.java
  server/src/main/java/com/example/server/repository/GameOrderRepository.java
  server/src/main/java/com/example/server/service/ChatService.java
Labels: feature, 백엔드, 김종경

#208 정답어 뿌리기 경고기능 추가
  client/package-lock.json
  client/package.json
  client/src/Game/ReadyToGame.tsx
  client/src/components/button/Button.tsx
  client/src/components/button/IconButton.tsx
  client/src/components/chatRoom/Tooltip.tsx
  client/src/components/ingameComponents/InGameUser.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/index.tsx
  client/src/types/dto.ts
  client/tailwind.config.js
Labels: feature, 프론트엔드, 하준서

#210 머지 후 코드수정
  client/src/Game/ReadyToGame.tsx
  client/src/components/button/Button.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/index.tsx
  client/src/types/common.ts
Labels: fix, 프론트엔드, 하준서

#215 feature/#213-정답자_순서_제외
  server/src/main/java/com/example/server/service/ChatService.java
Labels: feature, 백엔드, 김종경

#222 질문-답변 턴 방식 게임 로직 완성, 게임 화면 UI 추가 및 개선
  client/package-lock.json
  client/src/Game/ReadyToGame.tsx
  client/src/components/chatRoom/ChatRoom.tsx
  client/src/components/radioButton/RadioButton.tsx
  client/src/index.tsx
  client/src/main/MainPage.tsx
  client/src/types/dto.ts
  client/tailwind.config.js
Labels: feature, 프론트엔드, 김준서

#226 release 배포
  client/package-lock.json
  client/src/Game/ReadyToGame.tsx
  client/src/components/chatRoom/ChatRoom.tsx
  client/src/components/radioButton/RadioButton.tsx
  client/src/index.tsx
  client/src/main/MainPage.tsx
  client/src/types/dto.ts
  client/tailwind.config.js
Labels: develop, 장홍준

#230 feature/#224-정답자_현재_턴_제거
  server/src/main/java/com/example/server/controller/ChatController.java
  server/src/main/java/com/example/server/repository/RoomUserRepository.java
  server/src/main/java/com/example/server/service/ChatService.java
Labels: feature, 백엔드, 김종경

#235 게임 결과화면 UI 제작
  client/package-lock.json
  client/package.json
  client/public/images/1st.png
  client/public/images/2nd.png
  client/public/images/3rd.png
  client/src/App.tsx
  client/src/Game/Ranking.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/ingameComponents/InGameUser.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/components/ingameComponents/RankingUser.tsx
  client/src/components/layout/FullLayout.tsx
  client/src/components/layout/Header.tsx
  client/src/components/party/Party.tsx
  client/src/components/party/Realistic.tsx
  client/src/index.css
  client/src/recoil/modal.ts
Labels: feature, 프론트엔드, 하준서

#275 경고 시 메시지 추가
  server/src/main/java/com/example/server/service/ChatService.java
Labels: feature, 백엔드, 김종경

#278 채팅창 초기화, 강제 턴 넘기기, 정답/종료 시 기능 추가
  client/src/Game/Ranking.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/chatRoom/ChatRoom.tsx
Labels: feature, 프론트엔드, 김준서

#282 feature/#281-05.24 테스트 수정 사항
  server/src/main/java/com/example/server/dto/ChatMessage.java
  server/src/main/java/com/example/server/service/ChatService.java
Labels: feature, 백엔드, 김종경

#283 release
  server/src/main/java/com/example/server/dto/ChatMessage.java
  server/src/main/java/com/example/server/service/ChatService.java
Labels: develop

#307 feature/#304-에외처리 & 게임 종료 시 정답어 리턴
  server/src/main/java/com/example/server/dto/GameUserDto.java
  server/src/main/java/com/example/server/exception/AlreadyStartedRoomException.java
  server/src/main/java/com/example/server/service/ChatService.java
  server/src/main/java/com/example/server/service/RoomService.java
Labels: feature, 백엔드, 김종경

#309 순위표시 결과페이지 연동
  client/public/images/others.png
  client/src/App.tsx
  client/src/Game/Ranking.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/components/ingameComponents/RankingUser.tsx
  client/src/index.css
  client/src/main/MainPage.tsx
  client/src/types/dto.ts
Labels: feature, 프론트엔드, 하준서

#315 feature/#314-테스트 수정 사항
  server/src/main/java/com/example/server/controller/ChatController.java
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/domain/RoomUser.java
  server/src/main/java/com/example/server/dto/ChatMessage.java
  server/src/main/java/com/example/server/dto/UserDto.java
  server/src/main/java/com/example/server/exception/CantStartGameException.java
  server/src/main/java/com/example/server/service/ChatService.java
  server/src/main/java/com/example/server/service/RoomService.java
Labels: feature, 백엔드, 김종경

#320 턴마다 동시에 타이머 리셋 처리
  client/src/Game/ReadyToGame.tsx
Labels: feature, 프론트엔드, 김준서

#323 새로고침 UI수정
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/Game/timer/useTimer.ts
  client/src/components/button/IconButton.tsx
  client/src/components/chatRoom/ChatRoom.tsx
  client/src/components/chatRoom/UserMessage.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/components/ingameComponents/RankingUser.tsx
  client/src/components/layout/Header.tsx
  client/src/components/party/Realistic.tsx
  client/src/types/common.ts
Labels: feature, fix, 프론트엔드, 하준서

#329 feature/#328-카테고리 소켓 추카 및 관련 기능 추기
  server/src/main/java/com/example/server/controller/ChatController.java
  server/src/main/java/com/example/server/domain/Room.java
  server/src/main/java/com/example/server/dto/ChatMessage.java
  server/src/main/java/com/example/server/exception/CategoryException.java
  server/src/main/java/com/example/server/exception/NoSuchCategoryException.java
  server/src/main/java/com/example/server/payload/request/RoomCreateRequest.java
  server/src/main/java/com/example/server/payload/response/RoomResponse.java
  server/src/main/java/com/example/server/repository/AnswerListRepository.java
  server/src/main/java/com/example/server/service/ChatService.java
  server/src/main/java/com/example/server/service/RoomService.java
Labels: feature, 백엔드, 김종경

#337 #336 라운드 증가에 따른 힌트 제공 기능 추가
  server/src/main/java/com/example/server/payload/response/AnswerListResponse.java
  server/src/main/java/com/example/server/repository/GameOrderRepository.java
  server/src/main/java/com/example/server/service/ChatService.java
Labels: feature, 백엔드, 김종경

#348 #346 타이머 설정 기능 추가
  server/src/main/java/com/example/server/controller/ChatController.java
  server/src/main/java/com/example/server/domain/Room.java
  server/src/main/java/com/example/server/dto/ChatMessage.java
  server/src/main/java/com/example/server/payload/request/RoomCreateRequest.java
  server/src/main/java/com/example/server/payload/response/RoomResponse.java
  server/src/main/java/com/example/server/service/ChatService.java
  server/src/main/java/com/example/server/service/RoomService.java
Labels: feature, 백엔드, 김종경

#363 타이머 설정
  client/package-lock.json
  client/package.json
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/Game/timer/Timer.tsx
  client/src/Game/timer/styled.ts
  client/src/Game/timer/useTimer.ts
  client/src/components/chatRoom/ChatRoom.tsx
  client/src/components/modal/CaptainReadyModal.tsx
  client/src/components/modal/Modal.tsx
  client/src/components/modal/ReadyModal.tsx
  client/src/components/slider/Slider.tsx
  client/src/main/MainPage.tsx
  client/src/recoil/recoil.ts
  client/src/types/common.ts
  client/src/types/dto.ts
Labels: feature, 프론트엔드, 하준서

#372 레디 기능 오류 수정
  client/src/Game/ReadyToGame.tsx
Labels: fix, 프론트엔드, 김준서

#377 질문자 탈주시 타이머 RESET 오류 수정
  client/src/Game/ReadyToGame.tsx
Labels: fix, 프론트엔드, 김준서

#380 #379 힌트 제공 시 띄어쓰기 처리
  server/src/main/java/com/example/server/service/ChatService.java
Labels: feature, 백엔드, 김종경

#384 색깔 바꾸는 코드 추가
  client/src/Game/ReadyToGame.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/types/dto.ts
Labels: feature, 프론트엔드, 하준서
