Repository pknu-wap/WAG, pull requests merged in 2024-04, with the labels that each got.

#29 refactor/필요없는 파일 삭제
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/repository/RoomRepositoryy.java
Labels: refactor, 백엔드, 김종경

#39 게임 플레잉 페이지 UI제작
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/GamePlaying/GamePlaying.tsx
  client/src/components/button/IconButton.tsx
  client/src/components/layout/Header.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/main/MainPage.tsx
  client/src/pages/GamePlaying.tsx
  client/src/pages/MakeRoom.tsx
Labels: feature, 프론트엔드, 하준서

#44 full layout 그리고 이미지 파일 업로드
  client/public/images/WAG_dark.2.png
  client/public/images/WAG_dark.3.png
  client/public/images/WAG_white.2.png
  client/public/images/WAG_white.3.png
  client/src/App.tsx
  client/src/GamePlaying/GamePlaying.tsx
  client/src/components/button/Button.tsx
  client/src/components/button/IconButton.tsx
  client/src/components/layout/FullLayout.tsx
  client/src/index.css
  client/src/main/MainPage.tsx
Labels: feature, 프론트엔드, 하준서

#55 [feature]네이버 OAuth 로그인 구현
  server/src/main/java/com/example/server/domain/AuthProvider.java
  server/src/main/java/com/example/server/security/oauth2/user/NaverOAuth2UserInfo.java
  server/src/main/java/com/example/server/security/oauth2/user/OAuth2UserInfoFactory.java
Labels: feature, 백엔드, 김종경

#57 [feature] 방장 설정 페이지 UI 제작 및 radio버튼 컴포넌트 제작
  client/src/CreateRoom/CreateRoom.tsx
  client/src/components/radioButton/RadioButton.tsx
Labels: feature, 프론트엔드, 김준서

#61 프론트 게임로직
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Game/GamePlaying.tsx
  client/src/Game/JoinGame.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/api/gameroomInfo.ts
  client/src/api/index.ts
  client/src/api/joinRoom.ts
  client/src/components/button/Button.tsx
  client/src/components/button/IconButton.tsx
  client/src/components/layout/FullLayout.tsx
  client/src/hooks/useDarkMode.tsx
  client/src/index.tsx
  client/src/types/common.ts
  client/src/types/dto.ts
  client/tailwind.config.js
Labels: feature, 프론트엔드, 하준서

#63 배포용 브랜치 최신화
  README.md
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/GamePlaying.tsx
  client/src/Game/JoinGame.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/api/gameroomInfo.ts
  client/src/api/index.ts
  client/src/api/joinRoom.ts
  client/src/components/button/Button.tsx
  client/src/components/button/IconButton.tsx
  client/src/components/layout/FullLayout.tsx
  client/src/components/radioButton/RadioButton.tsx
  client/src/hooks/useDarkMode.tsx
  client/src/index.tsx
  client/src/types/common.ts
  client/src/types/dto.ts
  client/tailwind.config.js
  server/src/main/java/com/example/server/controller/NickNameController.java
Labels: develop

#68 프론트 게임로직2
  client/package-lock.json
  client/package.json
  client/src/Game/JoinGame.tsx
  client/src/api/gameroomInfo.ts
  client/src/components/button/Button.tsx
  client/src/components/modal/Modal.tsx
  client/src/index.tsx
  client/src/main/MainPage.tsx
  client/src/recoil/modal.ts
  client/src/types/dto.ts
  client/tailwind.config.js
Labels: feature, 프론트엔드, 하준서, 김준서

#70 게임 로직 2 완료 & 테스트 필요
  server/src/main/java/com/example/server/controller/ChatController.java
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/dto/ChatGameMessage.java
  server/src/main/java/com/example/server/dto/ChatMessage.java
  server/src/main/java/com/example/server/dto/ChatRoomInfoMessage.java
  server/src/main/java/com/example/server/dto/ChatRoomModeMessage.java
  server/src/main/java/com/example/server/dto/UserDto.java
  server/src/main/java/com/example/server/exception/MaxUserCountExceededException.java
  server/src/main/java/com/example/server/repository/RoomUserRepository.java
  server/src/main/java/com/example/server/service/ChatService.java
  server/src/main/java/com/example/server/service/RoomService.java
Labels: feature, 백엔드, 김종경

#74 [feature] 페이지별 라우팅 설정
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/CreateRoom/CreateRoom.tsx
  client/src/main/MainPage.tsx
Labels: feature, 프론트엔드, 김준서

#76 닉네임 api 수정
  server/src/main/java/com/example/server/controller/NickNameController.java
  server/src/main/java/com/example/server/repository/RoomUserRepository.java
  server/src/main/java/com/example/server/service/NickNameService.java
Labels: 백엔드, 김종경, modify

#79 파비콘, 웹타이틀 변경
  client/public/favicon.ico
  client/public/index.html
  client/src/main/MainPage.tsx
  package-lock.json
Labels: chore, 프론트엔드, 김준서

#83 클라이언트 소켓 연결 및 구독
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/radioButton/RadioButton.tsx
  client/src/main/MainPage.tsx
Labels: feature, 프론트엔드, 하준서, 김준서
