Repository pknu-wap/WAG, pull requests merged in 2024-06, with the labels that each got.

#387 경고주기 툴팁 컴포넌트 수정
  client/package-lock.json
  client/package.json
  client/src/Game/ReadyToGame.tsx
  client/src/components/chatRoom/ChatRoom.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/components/layout/FullLayout.tsx
  client/src/components/popover/Popover.tsx
  client/src/index.css
  client/tailwind.config.js
Labels: fix, 프론트엔드, 하준서

#389 게임 진행과정 개선
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/chatRoom/ChatRoom.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/index.css
  client/src/recoil/recoil.ts
  client/src/types/dto.ts
Labels: fix, 프론트엔드, 하준서

#394 프론트 오류 수정
  client/src/Game/ReadyToGame.tsx
Labels: fix, 프론트엔드, 하준서

#398 Feature/#355 사옹자 UI 개선
  client/package-lock.json
  client/package.json
  client/public/images/WAG_dark.2.png
  client/public/images/WAG_white.2.png
  client/src/Game/ReadyToGame.tsx
  client/src/components/modal/CaptainReadyModal.tsx
  client/src/components/modal/Modal.tsx
  client/src/components/modal/ReadyModal.tsx
  client/src/index.css
  client/src/main/MainPage.tsx
Labels: feature, 프론트엔드, 장홍준

#399 닉네임 확인 버튼
  client/src/Game/ReadyToGame.tsx
Labels: fix, 프론트엔드, 하준서

#401 fix : recoil 주소 변경
  client/src/components/modal/CaptainReadyModal.tsx
  client/src/components/modal/Modal.tsx
  client/src/components/modal/ReadyModal.tsx
Labels: fix, 프론트엔드, 장홍준

#404 #403 게임 종료 로직 수정
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/domain/Room.java
  server/src/main/java/com/example/server/service/ChatService.java
Labels: feature, fix, 김종경

#410 프론트 오류수정
  client/src/Game/ReadyToGame.tsx
Labels: fix, 프론트엔드, 하준서

#412 모바일 UI 제작
  client/src/Game/ReadyToGame.tsx
  client/src/Game/RedayStartButton.tsx
  client/src/components/button/Button.tsx
  client/src/components/button/IconButton.tsx
  client/src/components/chatRoom/NotificationMessage.tsx
  client/src/components/chatRoom/UserMessage.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/tailwind.config.js
Labels: feature, 프론트엔드, 하준서

#417 feat : 음악 추가
  client/public/audio/main_theme.mp3
  client/src/components/button/Button.tsx
  client/src/components/layout/Header.tsx
Labels: feature, 프론트엔드, 장홍준

#420 test : 배경음악 효과음 에러 테스트
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/layout/Header.tsx
  client/src/main/MainPage.tsx
Labels: feature, 프론트엔드, 장홍준

#427 UI 수정
  client/src/Game/ReadyToGame.tsx
  client/src/components/chatRoom/NotificationMessage.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/components/modal/CaptainReadyModal.tsx
  client/src/components/modal/LoadingModal.tsx
  client/src/components/modal/Modal.tsx
  client/src/components/modal/ReadyModal.tsx
  client/src/components/modal/RulesModal.tsx
  client/src/main/MainPage.tsx
Labels: fix, 프론트엔드, 하준서

#434 fix : 방 생성 모달 배치 에러 해결
  client/src/components/modal/RulesModal.tsx
Labels: feature, 프론트엔드, 장홍준

#437 모달 높이 수정 완
  client/src/components/modal/CaptainReadyModal.tsx
  client/src/components/modal/RulesModal.tsx
Labels: fix, 프론트엔드, 하준서

#443 웹사이트 Open Graph 정보 설정, 썸네일 이미지 추가
  client/public/images/WAG_Preview_image2.png
  client/public/images/WAG_main_page.png
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
Labels: feature, 프론트엔드, 김준서

#445 WAG 사이트 구글 애널리틱스, 서치콘솔 등록
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/sitemap.xml
  client/src/App.tsx
  client/src/util/RouteChangeTracker.jsx
Labels: feature, 프론트엔드, 김준서

#448 변경 완
  client/src/Game/ReadyToGame.tsx
  client/src/components/chatRoom/UserMessage.tsx
Labels: feature, 프론트엔드, 하준서

#451 Fix/#436 모바일을 위한 UI 변경
  client/package-lock.json
  client/package.json
  client/src/Game/ReadyToGame.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/components/party/Realistic.tsx
Labels: feature, 프론트엔드, 장홍준

#457 #456-cycle_에러_수정
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/service/ChatService.java
Labels: fix, 백엔드, 김종경
