Repository pknu-wap/WAG, pull requests merged in 2024-03, with the labels that each got.

#2 초기 세팅 및 구글, 깃허브 OAuth 로그인
  .github/pull_request_template.md
Labels: chore, 백엔드, 김종경

#8 #5 Merge test
  client/src/App.js
Labels: chore, 프론트엔드, 김준서

#11 feature/#9-웹 소켓
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/repository/ChatRoomRepository.java
Labels: feature, 백엔드, 김종경

#16 feature/#09-dto 이름 수정
  server/build/classes/java/main/com/example/server/controller/ChatController.class
  server/build/classes/java/main/com/example/server/domain/ChatRoom.class
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/src/main/java/com/example/server/controller/ChatController.java
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/domain/ChatRoom.java
  server/src/main/java/com/example/server/domain/Room.java
  server/src/main/java/com/example/server/dto/RoomDto.java
  server/src/main/java/com/example/server/repository/ChatRoomRepository.java
  server/src/main/java/com/example/server/repository/RoomRepository.java
Labels: feature, 백엔드, 김종경

#18 수정
  server/src/main/java/com/example/server/config/WebSocketConfig.java
  server/src/main/java/com/example/server/controller/ChatController.java
Labels: refactor, 백엔드, 김종경

#22 feature/#09-방 생성 & 방 정보 받기 API 완료
  server/build/classes/java/main/com/example/server/config/WebSocketConfig.class
  server/build/classes/java/main/com/example/server/controller/ChatController.class
  server/build/classes/java/main/com/example/server/domain/ChatMessage$MessageType.class
  server/build/classes/java/main/com/example/server/domain/ChatMessage.class
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/src/main/java/com/example/server/controller/ChatController.java
  server/src/main/java/com/example/server/controller/WebSocketEventListener.java
  server/src/main/java/com/example/server/domain/ChatGameMessage.java
  server/src/main/java/com/example/server/domain/ChatMessage.java
  server/src/main/java/com/example/server/domain/Room.java
  server/src/main/java/com/example/server/domain/RoomUser.java
  server/src/main/java/com/example/server/dto/GameUserDto.java
  server/src/main/java/com/example/server/dto/RoomDto.java
  server/src/main/java/com/example/server/dto/UserDto.java
  server/src/main/java/com/example/server/payload/RoomCreateRequest.java
  server/src/main/java/com/example/server/payload/RoomResponse.java
  server/src/main/java/com/example/server/repository/RoomRepository.java
  server/src/main/java/com/example/server/repository/RoomRepositoryy.java
  server/src/main/java/com/example/server/repository/RoomUserRepository.java
  server/src/main/java/com/example/server/service/ChatService.java
Labels: feature, 백엔드, 김종경

#25 방 관련 api & 채팅 기능
  server/build/classes/java/main/com/example/server/config/SecurityConfig.class
  server/build/classes/java/main/com/example/server/config/WebSocketConfig.class
  server/build/classes/java/main/com/example/server/controller/ChatController.class
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/src/main/java/com/example/server/config/SecurityConfig.java
  server/src/main/java/com/example/server/config/WebSocketConfig.java
  server/src/main/java/com/example/server/controller/ChatController.java
  server/src/main/java/com/example/server/controller/RoomController.java
  server/src/main/java/com/example/server/dto/UserDto.java
  server/src/main/java/com/example/server/payload/RoomEnterResponse.java
  server/src/main/java/com/example/server/payload/RoomResponse.java
  server/src/main/java/com/example/server/repository/RoomRepository.java
  server/src/main/java/com/example/server/repository/RoomUserRepository.java
  server/src/main/java/com/example/server/service/ChatService.java
  server/src/main/java/com/example/server/service/RoomService.java
Labels: feature, 백엔드, 김종경

#27 feature/#26-닉네임 관련 api
  server/build/classes/java/main/com/example/server/controller/AuthController.class
  server/build/classes/java/main/com/example/server/controller/ChatController.class
  server/build/classes/java/main/com/example/server/payload/ApiResponse.class
  server/build/classes/java/main/com/example/server/payload/AuthResponse.class
  server/build/classes/java/main/com/example/server/payload/LoginRequest.class
  server/build/classes/java/main/com/example/server/payload/SignUpRequest.class
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/src/main/java/com/example/server/controller/AuthController.java
  server/src/main/java/com/example/server/controller/ChatController.java
  server/src/main/java/com/example/server/controller/NickNameController.java
  server/src/main/java/com/example/server/controller/RoomController.java
  server/src/main/java/com/example/server/payload/request/LoginRequest.java
  server/src/main/java/com/example/server/payload/request/RoomCreateRequest.java
  server/src/main/java/com/example/server/payload/request/SignUpRequest.java
  server/src/main/java/com/example/server/payload/response/ApiResponse.java
  server/src/main/java/com/example/server/payload/response/AuthResponse.java
  server/src/main/java/com/example/server/payload/response/NickNameResponse.java
  server/src/main/java/com/example/server/payload/response/RoomEnterResponse.java
  server/src/main/java/com/example/server/payload/response/RoomResponse.java
  server/src/main/java/com/example/server/repository/RoomUserRepository.java
  server/src/main/java/com/example/server/service/ChatService.java
  server/src/main/java/com/example/server/service/NickNameService.java
  server/src/main/java/com/example/server/service/RoomService.java
Labels: feature, 백엔드, 김종경
