Repository pknu-wap/WAG, pull requests merged in 2025-06, with the labels that each got.

#513 [refactor] API URL 환경변수로 분리
  client/src/CreateRoom/CreateRoom.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/ingameComponents/JoinUser.tsx
  client/src/main/MainPage.tsx
  client/src/types/dto.ts
Labels: fix, 김준서

#518 release
  client/.gitignore
  client/src/components/layout/Footer.tsx
  client/src/components/layout/Header.tsx
  client/src/index.tsx
Labels: release

#519 release
  client/src/components/layout/Footer.tsx
  client/src/main/MainPage.tsx
Labels: release

#533 robots.txt 배포
  client/public/robots.txt
Labels: release

#534 [release] fix : change ads.txt to Ads.txt and change robots.txt for crawling
  client/public/Ads.txt
  client/public/robots.txt
Labels: release

#536 feat : 구글 애드센스 스크립트 추가
  client/public/index.html
Labels: release

#542 [release] 구글 애드센스 스크립트 추가 테스트 2
  client/public/index.html
Labels: release

#537 [feat] 새로고침 후 예외 처리, 브라우저 제한 해제, 임원진 리스트 제거 외 버그들 해결
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/dropDown/DropDown.tsx
  client/src/components/layout/Header.tsx
  client/src/components/qrGenerator/QRCodeGenerator.tsx
  client/src/main/MainPage.tsx
Labels: feature, fix, 프론트엔드, 장홍준

#543 [release]
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Game/ReadyToGame.tsx
  client/src/components/dropDown/DropDown.tsx
  client/src/components/layout/Header.tsx
  client/src/components/qrGenerator/QRCodeGenerator.tsx
  client/src/main/MainPage.tsx
Labels: release

#544 [release] 새로고침 시 바로 퇴장 기능으로 유령방 UI 버그 해결
  client/src/Game/ReadyToGame.tsx
Labels: release
